### ISSUE TITLE
Error boot execution git not found

### ISSUE THREAD

**Issue by m-hari16** [milisecond/wilayah-administrasi-indonesia#6]
![Screenshot from 2022-07-03 21-00-51](https://user-images.githubusercontent.com/54405674/177043410-a1155de0-3b00-4c5a-854e-32b0098754d3.png)

**Comment by zidnim5** [comment]
Ok noted, i will update it as soon as possible

**Comment by m-hari16** [comment]
Please update your job

**Comment by m-hari16** [comment]
good job
